### ISSUE TITLE
Should hawtio plugin retain use of the @hawtiosrc alias

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#105]
Due to the introduction of a new package (camel-model), the `@hawtio` ident prioritizes the new purpose of being an organisation. In order to avoid confusion and failure, the ident referencing src paths is modified to `@Hawtiosrc` (see https://github.com/hawtio/hawtio-next/pull/93).

Is this the correct alias?
Should this alias even be retained or is there something better?

**Comment by tadayosi** [comment]
When I introduced original `@hawtio` alias, it was designed so that each module can be independent of outer modules by not needing to refer to them using relative path `../` and make it self-contained with their own files under its own directory.

But with the code growing, it might be that with the usage of the local alias we have more to lose than to gain. Maybe we should remove the alias and just use relative path to import outer modules.

**Comment by tadayosi** [comment]
At the same time, use of relative paths can be another source of annoyance.
https://stackoverflow.com/questions/43281741/how-to-use-paths-in-tsconfig-json

Possible candidates for better alias naming:
- `@hawtio-src`
- `@hawtio-root`
- `@package-root`
- `@src`
- `__hawtio__`
- `__src__`

**Comment by tadayosi** [comment]
We keep using `@hawtiosrc`. Until we come up with better name, we can close it for now.
