### ISSUE TITLE
Camel - Endpoints view

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio-next#21]
Camel plugin should provide the view for managing Camel endpoints from the web console, which includes:

- Add a new endpoint
- Browse messages in an endpoint
- Send a test message to an endpoint

![Endpoints](https://user-images.githubusercontent.com/156692/213159823-47b2359b-d36f-4a1c-9dac-4555e1244869.png)

**Comment by phantomjinx** [comment]
Depends on https://github.com/hawtio/hawtio-next/pull/196

**Comment by phantomjinx** [comment]
Due to the [componentParameterJsonSchema](https://camel.apache.org/manual/camel-3-migration-guide.html#_removed_jmx_apis_for_explaining_eips_components_etc) bean being no longer included in camel version 3, the schema of the components needs to be fetched from the camel-catalog. However, the latter does not at this time include the components.

So depends on https://github.com/hawtio/hawtio-next/issues/79
