### ISSUE TITLE
Some link texts missing spaces inside sentences

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#336]
Some link texts are missing spaces when used inside sentences. 

For example, when you are on Connect page and expand the Hint, you will see the text with link texts which are missing spaces

<img width="1701" alt="Screenshot 2023-06-12 at 11 31 16" src="https://github.com/hawtio/hawtio-next/assets/49488040/e46f3bda-2e72-41e3-b74d-a138b986e4ff">

**Comment by joshiraez** [comment]
They are missing a `{' '}`before the link. It has also to be done after any line breaks because there is no way to put a space there.

I think it's a good first issue if anyone wants to take care of it. It can be seen how can it be used in those pages
![image](https://github.com/hawtio/hawtio-next/assets/17336236/2819a1bd-6a47-4106-8eaf-488a3235fb90)
it's just adding a few more and making sure it's ok.

I can take care of this as well if noone picks it after some time.

**Comment by Msarawan** [comment]
@tadayosi i am currently working on this issue.

**Comment by tadayosi** [comment]
@Msarawan Assignment is reserved for the core developer team members. You don't need to get assgined to it to start working on it. Everyone knows that you're working on it already.

**Comment by Msarawan** [comment]
> @Msarawan Assignment is reserved for the core developer team members. You don't need to get assgined to it to start working on it. Everyone knows that you're working on it already.

okay, Thanks!

**Comment by Msarawan** [comment]
can anyone please confirm is there any proper format/way is followed for committing the code.
