### ISSUE TITLE
[Enhancement] Can we add Camel Message Headers recommendations?

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#339]
In the past there was a feature helping to find the correct Camel Message Header when start typing it as shown below

![Screenshot 2023-06-12 at 17 00 26](https://github.com/hawtio/hawtio-next/assets/49488040/5a649b0a-a31d-41ac-8eac-2985e034c85c)

In new Hawtio this feature is missing

![Screenshot 2023-06-12 at 17 03 37](https://github.com/hawtio/hawtio-next/assets/49488040/4524fd49-efc0-41d8-9125-47323668a483)

**Comment by mmelko** [comment]
I will look at this, thanks for pointing this out!

**Comment by mmelko** [comment]
@tadayosi  I reopened this. I did suggestions in "forward" messages view not here. For this one we need something like: https://github.com/hawtio/hawtio-integration/blob/main/plugins/camel/ts/camelHeaderSchema.ts which should be generated out of : https://github.com/apache/camel/blob/41e0df411bf80104f10929d8d80392564cbcaf72/core/camel-api/src/main/java/org/apache/camel/Exchange.java#L66

So I can generate the file manually, do the suggestions and then I will have to implement it in camel-catalog-schema-generator-plugin later to have the headers always up to date. I don't think the Exchange interface is changing that often so I don't think it's critical to have it auto-generated since the beginning, WDYT ?

**Comment by tadayosi** [comment]
Looks like it's not me but @joshiraez who caused it to be closed :smiley: 

> So I can generate the file manually, do the suggestions and then I will have to implement it in camel-catalog-schema-generator-plugin later to have the headers always up to date. I don't think the Exchange interface is changing that often so I don't think it's critical to have it auto-generated since the beginning, WDYT ?

That sounds good to me, but the initial model is based on the latest Exchange from Camel 3.20.x LTS, not just copying from the legacy code, correct?

**Comment by mmelko** [comment]
correct. I will create it from the LTS version :)

**Comment by joshiraez** [comment]
Sorry, it was me. I thought it was the same issue. My bad

**Comment by tadayosi** [comment]
Should be fixed with #388 finally.
