### ISSUE TITLE
[Bug] XNIO-2 node under XNIO folder doesn't have correct IDs

### ISSUE THREAD

**Issue by joshiraez** [hawtio/hawtio-next#377]
![image](https://github.com/hawtio/hawtio-next/assets/17336236/6e998432-b8ac-4fcb-aced-912b879c6496)

As far as I have seen it is the only outlier. My best guess is that somehow the XNIO-2 folder it's created, then it adopts its children and because the adopt() function doesn't regenerate the ids for the tree, it doesn't update.

I'm currently checking how the JMX tree is created in order to find why the ids didn't update for that particular case.

**Comment by joshiraez** [comment]
I'm submitting a fix and we have a test now that checks for ids in domain and mock trees. If there are any further issues we can further review how ids are generated

**Comment by tadayosi** [comment]
OK, I found the root cause. It is that, when we first populate the mbean tree, there's a wrong expectation that the children of a folder have unique names and the code looks up the existing children only with a name. But in reality there can be two nodes with the same name, one is a mbean and the other is a folder. And depending on the order of mbeans Hawtio receives, the first node can be an mbean (in the above case `org.xnio:type=Xnio,provider="nio",worker="XNIO-2"`) and the code tries to add children to the leaf mbean node.

Let me fix the issue.
