### ISSUE TITLE
Broken views in Charts

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#437]
There are several issues with Charts

1. Time is missing hours

2. Missing values - you have to hover a mouse pointer to view a value

3. Missing an Y-Axis in the charts - it could help to see the values immediately

<img width="1728" alt="Screenshot 2023-07-18 at 10 02 23" src="https://github.com/hawtio/hawtio-next/assets/49488040/b2430979-bf2b-4ce9-ad08-b69013ddb57e">

**Comment by lhein** [comment]
@joshiraez could you have a look at that issue once you are back?

**Comment by lhein** [comment]
this issue relates to #10

**Comment by joshiraez** [comment]
I'm on sick leave right now but I can address the questions.

1) Hours are not really worth it as most data gets wiped out after you get out of the screen. I tried having it but it clutters the timeline a lot, and most times you know that it's in your time proximity.

This limitation it's similar to the original, where data would get wiped out in a lot of instances - at least, now, it should be consistent in that you should have all the data while you are on the view.

Being able to pull more data was one of my original design goals at first but I was asked to just mimic the old hawtIO behaviour instead of improving it, so I could just make sure that it was at least consistent while you were on the view.

Adding the hours is easy enough if you feel like it's really needed. It's just that you could see that as soon as we have a lot of entries, you'll have very little ticks showing the times and you could most easily guess those.

On top of that, on hover you will actually see the full time with hours along with the values.

2) Yes. This is how it worked in the original where you had to hover over a point to see the actual values. How would you like those being shown? Although keep in mind that patternfly charts have some limitations, I would have to ask their team and Victory charts again, but it can be looked at.

3) Because the domains for the data are so wildly varying, adding the Y axis usually resulted in something like this.

- 389274987218937213
- 148390821309809482 
- 0

Which, on top of wasting a lot of space again, I felt like they didn't add any value. This is consistent with the original as well, as you don't have Y axis in none of the charts, only having a common time x-axis for every one.

If you'd like to have a diferent design, please tell me your suggestions and we can take a look at it in a different ticket to improve into it. Sorry for not being of more help on this, as most of the things are actually expected and takeovers from the original version.
