### ISSUE TITLE
Camel Components page is missing components table and other things

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#438]
Camel Components page is missing Components table and other tabs

![Screenshot 2023-07-18 at 11 09 46](https://github.com/hawtio/hawtio-next/assets/49488040/72af1623-7f8d-44b5-939c-79bb5a4a1cca)

It has only Send Massage feature.

In older Hawtio it had Attribute table, Operations, Chart

![Screenshot 2023-07-18 at 11 13 20](https://github.com/hawtio/hawtio-next/assets/49488040/7fe7129f-9e6c-43e9-b82b-26c5e6e7f413)

**Comment by joshiraez** [comment]
This also breaks JMX as JMX uses the Camel Plugin for Camel nodes.

**Comment by tadayosi** [comment]
@joshiraez No, it was just refactoring and nothing should be changed functionally. We assigned it to you so please have a look.

**Comment by tadayosi** [comment]
Sorry I was confused with the other issue. Let me have a look.

**Comment by tadayosi** [comment]
It should be already fixed with https://github.com/hawtio/hawtio-next/commit/38d50e18b42249df8051109d5e3ca7db03fca95f.

@jsolovjo I think you've been testing it with 0.3.0 or 0.4.0-dev.1. Can you confirm that with the latest `main` branch?

**Comment by tadayosi** [comment]
By the way, when the view has only one tab I intentionally hide the tab nav to earn extra vertical space. So the issue was not that tabs are not visible but the wrong view was chosen.
https://github.com/hawtio/hawtio-next/blob/09983daabde8e930f0b6508470b3344681c8b269/packages/hawtio/src/plugins/camel/CamelContent.tsx#L169

On a separate note, we can discuss whether we should display the nav even if we only have one tab.

**Comment by jsolovjo** [comment]
Hi @tadayosi yes I tested it with `0.4.0-dev.1`

**Comment by tadayosi** [comment]
@jsolovjo Now `0.4.0-dev.2` is released with the latest fixes and is applied to the hawtio standalone project branch as well. Please check it with the latest branch.
https://github.com/hawtio/hawtio/commit/5937a296ae7b103a0f895855c31f3a05c2e7d4fb
