### ISSUE TITLE
Hawtio on Quarkus is missing Camel Route Debug feature

### ISSUE THREAD

**Issue by jsolovjo** [hawtio/hawtio-next#536]
Hello,

I have noticed that Hawtio on Quarkus is missing Camel Route Debug feature but it is present on Spring Boot - is it expected?
![1694012235926 0](https://github.com/hawtio/hawtio-next/assets/49488040/dbe80839-40f5-48dc-a0a4-3b48a21629e8)

Thank you

**Comment by jamesnetherton** [comment]
You need to have `camel-quarkus-debug` added to the application.

However, in Camel Quarkus 2.x, the implementation of that extension was a bit flawed in that it was only active in Quarkus development mode.

In 3.x it's been changed so that debugging / suspend can be enabled via some config properties:

https://camel.apache.org/camel-quarkus/next/reference/extensions/debug.html#extensions-debug-additional-camel-quarkus-configuration

**Comment by jsolovjo** [comment]
@jamesnetherton thank you for the information, I didn't know it
