### ISSUE TITLE
Camel - Import of the Camel Model Definitions

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#78]
The Camel model [schema](https://github.com/hawtio/hawtio-integration/blob/main/vendor/apache-camel/camelModel.js) is [imported](https://github.com/hawtio/hawtio-integration/blob/main/plugins/camel/ts/camelHelpers.ts#L23) into the old UI for icon lookup and model validation.

Maybe instead of importing it into a vendor directory, we should publish it as a separate npm package that is then brought in as a yarn dependency?

**Comment by phantomjinx** [comment]
Playing with some more am finding the overhead of the model being a module outweighs the reasons for it to be a separate package.

**Comment by tadayosi** [comment]
Actually I second your initial proposal. Making the Camel model JS a separate module sounds reasonable, especially considering that the module would require an extra dev dependency to interact with Maven artifacts from Camel as hawtio-integration currently does. Keeping it separate can make the `@hawtio/react` package simple.

Since we are already migrated to monorepo, why not just having the module under another package `packages/camel-model` within the hawtio-next project?  Then I don't see extra overhead of having it as a separate module.
