### ISSUE TITLE
Where is hawtio-json-schema-generator maven plugin now located?

### ISSUE THREAD

**Issue by phantomjinx** [hawtio/hawtio-next#79]
This maven plugin is used to generate the required version of the camel model json. It is published to [maven central](https://mvnrepository.com/artifact/io.hawt/hawtio-json-schema-generator-plugin) but the source is only available from the hawtio/hawtio [1.x branch](https://github.com/hawtio/hawtio/tree/1.x/hawtio-json-schema-generator/hawtio-json-schema-generator-plugin). It was then removed(?). Where is it now located if at all and if it was never moved elsewhere, should it be??

- [x] Issue [#1 - Tidy up Tasks](https://github.com/phantomjinx/hawtio-camel-catalog-schema-generator-plugin/issues/1)
- [x] Issue [#2 - Migrate project to hawtio organisation](https://github.com/phantomjinx/hawtio-camel-catalog-schema-generator-plugin/issues/2)

**Comment by tadayosi** [comment]
Right, we still uses 1.x version from the old branch because it just works fine. We can restore it to the latest 3.x branch if needed.

**Comment by phantomjinx** [comment]
> Right, we still uses 1.x version from the old branch because it just works fine. We can restore it to the latest 3.x branch if needed. Or you can use it as-is for the time being.

Might be good to publish it to its own repository. I'll maybe have a look at that next week.

**Comment by tadayosi** [comment]
Yes, splitting it into another repo under hawtio org is another option. I'm not sure if we can reuse the same settings and credentials to publish a Maven plugin to Maven Central, but please go ahead with the option.

**Comment by tadayosi** [comment]
@phantomjinx Thanks, that's great!  I think it's almost ok, but there are a few minor comments.

_Implementation_

* I see the impl still partly depends on a legacy part of Hawtio. I think the only needed dependency is `io.hawt.jsonschema.SchemaLookup`. Then, we can also copy it to the project and remove the dependency.
   
       <version.hawtio.json.schema.mbean>2.0-M3</version.hawtio.json.schema.mbean>
* Maybe we can stop using commons-lang, as the only usage seems to be `Validate.notNull()` and you can use `Objects.requireNonNull()` instead.

_Styling and structure_

* Let's use spaces for indentation (I see some files use tabs)
* Unless we plan to host more than one maven plugin, I don't think we need to have a nested Maven project structure. We could simply flatten it and move hawtio-camel-catalog-schema-generator-plugin top level.
* Once we transter it to hawtio org, we can rename it to hawtio/camel-catalog-schema-generator-plugin

That said, overall it looks great already and we can start improving it from here. Why don't we transfer the project to hawtio org?

I think the remaining thing to do is:

* Copy `release` profile and script from the main Hawtio project so that it can be published to Maven Central Repo.
   https://github.com/hawtio/hawtio/blob/main/pom.xml#L258-L327
   https://github.com/hawtio/hawtio/blob/main/bin/release
   (I'm not sure if we can use the same credentials for publishing the maven plugin as well, or we should file another JIRA ticket to OSSRH for this project again: https://central.sonatype.org/publish/publish-guide/)

**Comment by tadayosi** [comment]
One more question.

> Added components to model schema;

What does it mean from the Hawtio.next point of view?  Do we need to change the Camel plugin to utilise the new info from the model?

**Comment by phantomjinx** [comment]
> What does it mean from the Hawtio.next point of view? Do we need to change the Camel plugin to utilise the new info from the model?

The `camel-model` [package](https://github.com/hawtio/hawtio-next/blob/main/packages/camel-model/src) will end up with a new `camelModel.ts` once the co-ordinates in its [pom](https://github.com/hawtio/hawtio-next/blob/main/packages/camel-model/pom.xml#L34) will be updated. However, even before its published, I can update the `camelModel.ts` manually with a locally generated version.
